# Generated by Django 5.2.8 on 2025-11-28 06:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_id', models.CharField(db_index=True, help_text='Unique browser session ID', max_length=64)),
                ('uri', models.URLField(help_text='URL where XSS fired', max_length=2048)),
                ('origin', models.CharField(blank=True, max_length=512)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
                ('cookies', models.TextField(blank=True)),
                ('localstorage', models.TextField(blank=True)),
                ('sessionstorage', models.TextField(blank=True)),
                ('dom', models.TextField(blank=True, help_text='Captured HTML')),
                ('screenshot', models.TextField(blank=True, help_text='Base64 encoded screenshot')),
                ('page_links', models.TextField(blank=True, help_text='JSON array of page links')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser_info', models.TextField(blank=True, help_text='Parsed browser details')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('geolocation', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Your notes about this capture')),
                ('fired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fired_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='CollectedPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uri', models.URLField(max_length=2048)),
                ('html_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_pages', to='hunter.capture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for this payload', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Where you're using this payload")),
                ('collect_cookies', models.BooleanField(default=True)),
                ('collect_localstorage', models.BooleanField(default=True)),
                ('collect_sessionstorage', models.BooleanField(default=True)),
                ('collect_dom', models.BooleanField(default=True)),
                ('collect_screenshot', models.BooleanField(default=True)),
                ('collect_urls', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='capture',
            name='payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='hunter.payload'),
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('webhook_type', models.CharField(choices=[('discord', 'Discord'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('custom', 'Custom URL')], max_length=20)),
                ('webhook_url', models.URLField(max_length=512)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='capture',
            index=models.Index(fields=['bot_id'], name='hunter_capt_bot_id_ca7963_idx'),
        ),
        migrations.AddIndex(
            model_name='capture',
            index=models.Index(fields=['status'], name='hunter_capt_status_cb71e3_idx'),
        ),
        migrations.AddIndex(
            model_name='capture',
            index=models.Index(fields=['fired_at'], name='hunter_capt_fired_a_5c8067_idx'),
        ),
    ]
