# Generated by Django 4.2 on 2025-11-28 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("hunter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayloadLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("react", "React"),
                            ("vue", "Vue.js"),
                            ("angular", "Angular"),
                            ("nextjs", "Next.js"),
                            ("svelte", "Svelte"),
                            ("htmx", "HTMX/Alpine"),
                            ("dom_clobbering", "DOM Clobbering"),
                            ("csp_probe", "CSP Probes"),
                            ("mutation", "Mutation XSS"),
                            ("polyglot", "Polyglots"),
                            ("trusted_types", "Trusted Types"),
                            ("short", "Ultra-Short"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.TextField()),
                (
                    "context",
                    models.CharField(
                        blank=True, help_text="Where this payload works", max_length=255
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("char_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Payload Library Entry",
                "verbose_name_plural": "Payload Library",
                "ordering": ["category", "char_count"],
            },
        ),
        migrations.CreateModel(
            name="PayloadToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                (
                    "target_url",
                    models.URLField(
                        blank=True,
                        help_text="Expected target URL (optional)",
                        max_length=2048,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("use_count", models.IntegerField(default=0)),
                (
                    "max_uses",
                    models.IntegerField(
                        default=1, help_text="Max times token can be used (0=unlimited)"
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="hunter.payload",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payloadtoken",
            index=models.Index(fields=["token"], name="hunter_payl_token_9bca03_idx"),
        ),
        migrations.AddIndex(
            model_name="payloadtoken",
            index=models.Index(
                fields=["is_used"], name="hunter_payl_is_used_036d95_idx"
            ),
        ),
    ]
